"""DB Construction 4

Revision ID: 50e9b6870c4b
Revises: ae844e55067b
Create Date: 2026-01-02 18:38:42.658430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e9b6870c4b'
down_revision: Union[str, None] = 'ae844e55067b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # FIRST: Drop the foreign key that depends on the constraint
    op.drop_constraint(op.f('transactions_origin_account_fkey'), 'transactions', type_='foreignkey')
    # THEN: Drop the unique constraint and column
    op.drop_constraint(op.f('accounts_account_id_key'), 'accounts', type_='unique')
    op.drop_column('accounts', 'account_id')
    # FINALLY: Create new foreign key pointing to accounts.id
    op.create_foreign_key(None, 'transactions', 'accounts', ['origin_account'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_origin_account_fkey'), 'transactions', 'accounts', ['origin_account'], ['account_id'])
    op.add_column('accounts', sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False, comment='Account unique identifier'))
    op.create_unique_constraint(op.f('accounts_account_id_key'), 'accounts', ['account_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
