"""DB Construction 8

Revision ID: 52c446c9142f
Revises: 0f9bd9377bb4
Create Date: 2026-01-03 15:17:09.689082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.contrib.schemas import TransactionType


# revision identifiers, used by Alembic.
revision: str = '52c446c9142f'
down_revision: Union[str, None] = '0f9bd9377bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('origin_account_id', sa.UUID(), nullable=False, comment='Origin account UUID'))
    op.add_column('transactions', sa.Column('origin_account_number', sa.Integer(), nullable=False, comment='Origin account number'))
    
    # Create the ENUM type first using values from TransactionType enum
    transaction_type_enum = sa.Enum(*[e.value for e in TransactionType], name='transactiontype')
    transaction_type_enum.create(op.get_bind(), checkfirst=True)
    
    # Now alter the column to use the ENUM type
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               type_=transaction_type_enum,
               existing_comment='Type of transaction (e.g., deposit, withdrawal)',
               existing_nullable=False,
               postgresql_using='transaction_type::transactiontype')
    
    op.drop_constraint(op.f('transactions_origin_account_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['origin_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['origin_account_number'], ['account_number'])
    op.drop_column('transactions', 'origin_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('origin_account', sa.UUID(), autoincrement=False, nullable=False, comment='Origin account UUID'))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_origin_account_fkey'), 'transactions', 'accounts', ['origin_account'], ['id'])
    
    # Revert column to VARCHAR
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.Enum(*[e.value for e in TransactionType], name='transactiontype'),
               type_=sa.VARCHAR(length=50),
               existing_comment='Type of transaction (e.g., deposit, withdrawal)',
               existing_nullable=False)
    
    # Drop the ENUM type
    sa.Enum(name='transactiontype').drop(op.get_bind(), checkfirst=True)
    
    op.drop_column('transactions', 'origin_account_number')
    op.drop_column('transactions', 'origin_account_id')
    # ### end Alembic commands ###
