"""datetime aware fix for all models

Revision ID: 5cf8bd71bef6
Revises: 65a1811b15eb
Create Date: 2026-01-03 17:08:52.068528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cf8bd71bef6'
down_revision: Union[str, None] = '65a1811b15eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('accounts', 'daily_withdrawal_limit',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Daily limit for successful withdrawal attempts',
               existing_nullable=False)
    op.alter_column('accounts', 'special_withdrawal_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_comment='Maximum amount allowed for special withdrawals',
               existing_nullable=False)
    op.alter_column('accounts', 'used_special_withdrawal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_comment='Amount already used from special withdrawal limit',
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Account creation timestamp',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Account creation timestamp',
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('accounts', 'used_special_withdrawal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_comment='Amount already used from special withdrawal limit',
               existing_nullable=False)
    op.alter_column('accounts', 'special_withdrawal_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'500'::double precision"),
               existing_comment='Maximum amount allowed for special withdrawals',
               existing_nullable=False)
    op.alter_column('accounts', 'daily_withdrawal_limit',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_comment='Daily limit for successful withdrawal attempts',
               existing_nullable=False)
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Creation timestamp',
               existing_nullable=False)
    # ### end Alembic commands ###
