"""DB Construction 6

Revision ID: 6419b635c44a
Revises: 9d86d1626221
Create Date: 2026-01-03 01:10:33.588100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6419b635c44a'
down_revision: Union[str, None] = '9d86d1626221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    op.add_column('users', sa.Column('user_fullname', sa.String(length=80), nullable=True, comment='User full name'))
    
    # Step 2: Update existing rows - derive from email or set default
    op.execute("""
        UPDATE users 
        SET user_fullname = COALESCE(
            SPLIT_PART(email, '@', 1),
            'Unknown User'
        )
        WHERE user_fullname IS NULL
    """)
    
    # Step 3: Make column NOT NULL now that all rows have values
    op.alter_column('users', 'user_fullname', nullable=False)
    
    # Drop username column and index
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Unique username'))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'user_fullname')
    # ### end Alembic commands ###
