"""DB Construction 10

Revision ID: 65a1811b15eb
Revises: abbb5e17ccfb
Create Date: 2026-01-03 16:38:34.339138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a1811b15eb'
down_revision: Union[str, None] = 'abbb5e17ccfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('daily_withdrawal_limit', sa.Integer(), nullable=False, server_default='5', comment='Daily limit for successful withdrawal attempts'))
    op.add_column('accounts', sa.Column('special_withdrawal_limit', sa.Float(), nullable=False, server_default='500.0', comment='Maximum amount allowed for special withdrawals'))
    op.add_column('accounts', sa.Column('used_special_withdrawal', sa.Float(), nullable=False, server_default='0.0', comment='Amount already used from special withdrawal limit'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'used_special_withdrawal')
    op.drop_column('accounts', 'special_withdrawal_limit')
    op.drop_column('accounts', 'daily_withdrawal_limit')
    # ### end Alembic commands ###
