"""DB Construction 2

Revision ID: 80a7780477e3
Revises: 8b815a11edcd
Create Date: 2026-01-02 17:18:30.409027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80a7780477e3'
down_revision: Union[str, None] = '8b815a11edcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_number', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('account_id', sa.UUID(), nullable=False, comment='Account unique identifier'),
    sa.Column('owner', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False, comment='Account type'),
    sa.Column('balance', sa.Float(), nullable=False, comment='Current balance'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Account password'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.uuid5'], ),
    sa.PrimaryKeyConstraint('account_number'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=True)
    op.drop_index(op.f('ix_example_entities_id'), table_name='example_entities')
    op.drop_table('example_entities')
    op.add_column('transactions', sa.Column('origin_account', sa.UUID(), nullable=False, comment='Origin account UUID'))
    op.add_column('transactions', sa.Column('transaction_type', sa.String(length=50), nullable=False, comment='Type of transaction (e.g., deposit, withdrawal)'))
    op.alter_column('transactions', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment='Transaction value',
               existing_comment='Numeric value')
    op.drop_index(op.f('ix_transactions_name'), table_name='transactions')
    op.create_foreign_key(None, 'transactions', 'accounts', ['origin_account'], ['account_id'])
    op.drop_column('transactions', 'name')
    op.drop_column('transactions', 'is_active')
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Entity description'))
    op.add_column('transactions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Active status'))
    op.add_column('transactions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Entity name'))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_index(op.f('ix_transactions_name'), 'transactions', ['name'], unique=False)
    op.alter_column('transactions', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='Numeric value',
               existing_comment='Transaction value')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'origin_account')
    op.create_table('example_entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Active status'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Creation timestamp'),
    sa.Column('account_number', sa.INTEGER(), autoincrement=False, nullable=False, comment='Primary key'),
    sa.Column('owner', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Account type'),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Current balance'),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Account password'),
    sa.ForeignKeyConstraint(['owner'], ['users.uuid5'], name=op.f('example_entities_owner_fkey'))
    )
    op.create_index(op.f('ix_example_entities_id'), 'example_entities', ['id'], unique=True)
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
