"""DB Construction

Revision ID: 8b815a11edcd
Revises: edcd54b26d6b
Create Date: 2026-01-02 16:46:39.385744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b815a11edcd'
down_revision: Union[str, None] = 'edcd54b26d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example_entities', sa.Column('account_number', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'))
    op.add_column('example_entities', sa.Column('owner', sa.UUID(), nullable=False))
    op.add_column('example_entities', sa.Column('account_type', sa.String(length=50), nullable=False, comment='Account type'))
    op.add_column('example_entities', sa.Column('balance', sa.Float(), nullable=False, comment='Current balance'))
    op.add_column('example_entities', sa.Column('password', sa.String(length=255), nullable=False, comment='Account password'))
    op.drop_index(op.f('ix_example_entities_name'), table_name='example_entities')
    op.create_foreign_key(None, 'example_entities', 'users', ['owner'], ['uuid5'])
    op.drop_column('example_entities', 'description')
    op.drop_column('example_entities', 'value')
    op.drop_column('example_entities', 'pk_id')
    op.drop_column('example_entities', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example_entities', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Entity name'))
    op.add_column('example_entities', sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Primary key'))
    op.add_column('example_entities', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Numeric value'))
    op.add_column('example_entities', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Entity description'))
    op.drop_constraint(None, 'example_entities', type_='foreignkey')
    op.create_index(op.f('ix_example_entities_name'), 'example_entities', ['name'], unique=False)
    op.drop_column('example_entities', 'password')
    op.drop_column('example_entities', 'balance')
    op.drop_column('example_entities', 'account_type')
    op.drop_column('example_entities', 'owner')
    op.drop_column('example_entities', 'account_number')
    # ### end Alembic commands ###
