"""DB Construction 9

Revision ID: abbb5e17ccfb
Revises: 52c446c9142f
Create Date: 2026-01-03 15:56:15.312739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbb5e17ccfb'
down_revision: Union[str, None] = '52c446c9142f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_origin_account_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'origin_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('origin_account_id', sa.UUID(), autoincrement=False, nullable=False, comment='Origin account UUID'))
    op.create_foreign_key(op.f('transactions_origin_account_id_fkey'), 'transactions', 'accounts', ['origin_account_id'], ['id'])
    # ### end Alembic commands ###
