"""DB Construction 3

Revision ID: ae844e55067b
Revises: 80a7780477e3
Create Date: 2026-01-02 17:47:54.936011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae844e55067b'
down_revision: Union[str, None] = '80a7780477e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Hashed account password'))
    op.drop_column('accounts', 'password')
    op.add_column('users', sa.Column('user_number', sa.String(length=30), nullable=False, comment='Governmental ID number'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Hashed user password',
               existing_comment='Hashed password',
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['user_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Hashed password',
               existing_comment='Hashed user password',
               existing_nullable=False)
    op.drop_column('users', 'user_number')
    op.add_column('accounts', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Account password'))
    op.drop_column('accounts', 'hashed_password')
    # ### end Alembic commands ###
