"""minor fixes and add destination_account_number column for transfers

Revision ID: b0042ae96fec
Revises: 5cf8bd71bef6
Create Date: 2026-01-03 18:29:09.861403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0042ae96fec'
down_revision: Union[str, None] = '5cf8bd71bef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('destination_account_number', sa.Integer(), nullable=True, comment='Destination account number (for transfers, optional when applicable)'))
    op.create_foreign_key(None, 'transactions', 'accounts', ['destination_account_number'], ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'destination_account_number')
    # ### end Alembic commands ###
