"""New Table Add

Revision ID: edcd54b26d6b
Revises: 001_example
Create Date: 2026-01-02 14:02:44.232860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edcd54b26d6b'
down_revision: Union[str, None] = '001_example'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('pk_id', sa.UUID(), nullable=False, comment='Primary key'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Entity name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Entity description'),
    sa.Column('value', sa.Float(), nullable=True, comment='Numeric value'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=True)
    op.create_index(op.f('ix_transactions_name'), 'transactions', ['name'], unique=False)
    op.create_index(op.f('ix_transactions_pk_id'), 'transactions', ['pk_id'], unique=False)
    op.create_table('users',
    sa.Column('uuid5', sa.UUID(), nullable=False, comment='uuid5 unique user identifier'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='User email address'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active status'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Admin privileges'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Account creation timestamp'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('uuid5')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid5'), 'users', ['uuid5'], unique=False)
    op.alter_column('example_entities', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID identifier',
               existing_nullable=False)
    op.drop_constraint(op.f('example_entities_id_key'), 'example_entities', type_='unique')
    op.drop_index(op.f('ix_example_entities_id'), table_name='example_entities')
    op.create_index(op.f('ix_example_entities_id'), 'example_entities', ['id'], unique=True)
    op.drop_table_comment(
        'example_entities',
        existing_comment='Example entities table',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'example_entities',
        'Example entities table',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_example_entities_id'), table_name='example_entities')
    op.create_index(op.f('ix_example_entities_id'), 'example_entities', ['id'], unique=False)
    op.create_unique_constraint(op.f('example_entities_id_key'), 'example_entities', ['id'], postgresql_nulls_not_distinct=False)
    op.alter_column('example_entities', 'id',
               existing_type=sa.UUID(),
               comment='UUID identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_uuid5'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_pk_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
